apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-for-fluent-bit
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::139592182912:role/introspect-aws-for-fluent-bit-irsa
