apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cl-02
  region: us-east-1
  version: "1.30"
  tags:
    karpenter.sh/discovery: cl-02
iam:
  withOIDC: true

managedNodeGroups:
  - name: mng-od-4vcpu-8gb
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    instanceType: t3.medium
    privateNetworking: true

addons:
  - name: vpc-cni 
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest 
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    wellKnownPolicies: 
      ebsCSIController: true