[project]
name = "order-service"
version = "0.1.0"
description = "Subscribes to product events via Dapr pub/sub"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.124.0",
]
