apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
  namespace: introspect
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "aws-otel-collector.observability.svc.cluster.local:4317"
      isSecure: false
      protocol: grpc
