apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-service-sa
  namespace: introspect
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::139592182912:role/introspect-product-service-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: introspect
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::139592182912:role/introspect-order-service-irsa
