apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-otel-collector
  namespace: observability
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::139592182912:role/introspect-aws-otel-collector-irsa
